defaults:
  pages:
  - graph
founders:
  sharath:
    pages:
    - dashboard
    - generate
    - customize
    - graph
    - coverage
    - workflow
    - history
    - config
  manisha:
    pages:
    - graph
  deepinder:
    pages:
    - graph
  raaid:
    pages:
    - graph
  anish_popli:
    pages:
    - graph
  purva:
    pages:
    - graph
  alok:
    pages:
    - graph
  vipul:
    pages:
    - graph
admin:
  password_hash: '$2b$12$pGOSz/X.KRoDBQzouYZWY.tXp58SLrQ/9ltRSQlJrKnHPLI7lerDS'
