"""Workflow node type registry — defines available node types for the visual builder."""

WORKFLOW_NODE_TYPES = {
    "topic_source": {
        "label": "Topic Source",
        "description": "Input node — provides the topic and platform",
        "inputs": 0,
        "outputs": 1,
        "category": "source",
    },
    "graph_source": {
        "label": "Knowledge Graph",
        "description": "Founder's knowledge graph data source",
        "inputs": 0,
        "outputs": 1,
        "category": "source",
    },
    "viral_source": {
        "label": "Viral Brain",
        "description": "Viral posts knowledge graph data source",
        "inputs": 0,
        "outputs": 1,
        "category": "source",
    },
    "topic_matcher": {
        "label": "Topic Matcher",
        "description": "Matches topic to knowledge graph beliefs, stories, models",
        "inputs": 1,
        "outputs": 1,
        "category": "agent",
        "executor": "match_topic_node",
    },
    "generator": {
        "label": "Post Generator",
        "description": "Generates 10 post variants using narrative engines",
        "inputs": 1,
        "outputs": 1,
        "category": "agent",
        "executor": "generate_all_posts_node",
    },
    "voter": {
        "label": "Audience Vote",
        "description": "5 audience agents score and critique all posts",
        "inputs": 1,
        "outputs": 1,
        "category": "agent",
        "executor": "audience_vote_node",
    },
    "selector": {
        "label": "Top Selector",
        "description": "Picks top 3 posts by aggregated audience score",
        "inputs": 1,
        "outputs": 1,
        "category": "agent",
        "executor": "select_top_node",
    },
    "refiner": {
        "label": "Refiner",
        "description": "Rewrites top posts incorporating audience feedback",
        "inputs": 1,
        "outputs": 1,
        "category": "agent",
        "executor": "refine_posts_node",
    },
    "massacre": {
        "label": "Opening Massacre",
        "description": "Generates 10 opening lines, audience votes on best one",
        "inputs": 1,
        "outputs": 1,
        "category": "agent",
        "executor": "opening_line_massacre_node",
    },
    "humanizer": {
        "label": "Humanizer",
        "description": "Applies humanization rules (style, vocabulary, rhythm)",
        "inputs": 1,
        "outputs": 1,
        "category": "agent",
        "executor": "humanize_node",
    },
    "quality_gate": {
        "label": "Quality Gate",
        "description": "Rule-based quality checks (75% threshold to pass)",
        "inputs": 1,
        "outputs": 2,
        "category": "agent",
        "executor": "quality_gate_node",
    },
    "coverage": {
        "label": "Coverage Tracker",
        "description": "Records which graph nodes influenced the post",
        "inputs": 1,
        "outputs": 1,
        "category": "agent",
        "executor": "track_coverage_node",
    },
    "custom_agent": {
        "label": "Custom Agent",
        "description": "User-defined prompt-based agent",
        "inputs": 1,
        "outputs": 1,
        "category": "custom",
        "executor": "custom_agent_node",
        "configurable": True,
    },
    "output": {
        "label": "Output",
        "description": "Final output sink — saves the generated post",
        "inputs": 1,
        "outputs": 0,
        "category": "output",
    },
}

# Default workflow configuration
DEFAULT_WORKFLOW = {
    "id": "default",
    "name": "Default Pipeline",
    "nodes": [
        {"id": "n1", "type": "topic_source", "position": {"x": 50, "y": 250}, "data": {"label": "Topic"}},
        {"id": "n2", "type": "topic_matcher", "position": {"x": 250, "y": 250}, "data": {"label": "Match Topic"}},
        {"id": "n3", "type": "generator", "position": {"x": 450, "y": 250}, "data": {"label": "Generate (10 engines)"}},
        {"id": "n4", "type": "voter", "position": {"x": 650, "y": 250}, "data": {"label": "Audience Vote"}},
        {"id": "n5", "type": "selector", "position": {"x": 850, "y": 250}, "data": {"label": "Select Top 3"}},
        {"id": "n6", "type": "refiner", "position": {"x": 1050, "y": 250}, "data": {"label": "Refine"}},
        {"id": "n7", "type": "massacre", "position": {"x": 250, "y": 450}, "data": {"label": "Opening Massacre"}},
        {"id": "n8", "type": "humanizer", "position": {"x": 450, "y": 450}, "data": {"label": "Humanize"}},
        {"id": "n9", "type": "quality_gate", "position": {"x": 650, "y": 450}, "data": {"label": "Quality Gate"}},
        {"id": "n10", "type": "coverage", "position": {"x": 850, "y": 450}, "data": {"label": "Track Coverage"}},
        {"id": "n11", "type": "output", "position": {"x": 1050, "y": 450}, "data": {"label": "Output"}},
    ],
    "edges": [
        {"id": "e1", "source": "n1", "target": "n2"},
        {"id": "e2", "source": "n2", "target": "n3"},
        {"id": "e3", "source": "n3", "target": "n4"},
        {"id": "e4", "source": "n4", "target": "n5"},
        {"id": "e5", "source": "n5", "target": "n6"},
        {"id": "e6", "source": "n6", "target": "n7"},
        {"id": "e7", "source": "n7", "target": "n8"},
        {"id": "e8", "source": "n8", "target": "n9"},
        {"id": "e9", "source": "n9", "target": "n10"},
        {"id": "e10", "source": "n10", "target": "n11"},
    ],
}
